"""Maintenance command: resolve exact tool pins to upstream wheel hashes."""
from __future__ import annotations

import json
import urllib.request

from scripts.supply_chain.common import HERE, canonical, require


def main() -> None:
    lines = ["# Generated by python -m scripts.supply_chain.lock_tools; wheels only."]
    evidence = []
    for line in (HERE / "requirements.txt").read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        requirement = line.split(";", 1)[0].strip()
        name, version = requirement.split("==")
        url = f"https://pypi.org/pypi/{name}/{version}/json"
        with urllib.request.urlopen(url, timeout=120) as response:
            metadata = json.load(response)
        wheels = sorted(
            [{"filename": f["filename"], "url": f["url"], "sha256": f["digests"]["sha256"]}
             for f in metadata["urls"] if f["packagetype"] == "bdist_wheel"],
            key=lambda f: f["filename"],
        )
        require(wheels, "missing-tool-wheels")
        lines.append(line + " \\")
        hashes = sorted({w["sha256"] for w in wheels})
        lines.extend("    --hash=sha256:" + sha + (" \\" if i < len(hashes) - 1 else "") for i, sha in enumerate(hashes))
        info = metadata["info"]
        evidence.append({
            "name": name, "version": version, "metadata_url": url,
            "declared": info.get("license_expression") or info.get("license"),
            "classifiers": [s for s in info.get("classifiers", []) if s.startswith("License ::")],
            "project_urls": info.get("project_urls"), "wheels": wheels,
        })
    (HERE / "requirements.lock").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (HERE / "python-tools.json").write_bytes(canonical({"packages": evidence}))


if __name__ == "__main__":
    main()
